// Code generated by internal/gen.tmpl, DO NOT EDIT.

package intset

import (
	"sync"
)

type set struct {
	mu   sync.RWMutex
	data map[int]struct{}
}

// New create and return instance of int set
func New(ints ...int) *set {
	s := NewWithSize(len(ints))
	s.Adds(ints...)
	return s
}

// New create and return instance of int set
func NewWithSize(size int) *set {
	return &set{
		data: make(map[int]struct{}, size),
	}
}

// Add item to the set.
func (s *set) Add(item int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	s.data[item] = struct{}{}
}

// Add items to the set.
func (s *set) Adds(items ...int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, item := range items {
		s.data[item] = struct{}{}
	}
}

// Remove item from the set.
func (s *set) Remove(item int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	delete(s.data, item)
}

// Remove items from the set.
func (s *set) Removes(items ...int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, item := range items {
		delete(s.data, item)
	}
}

// Exist determines whether the item is exists in the set.
func (s *set) Exist(item int) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	_, ok := s.data[item]
	return ok
}

// List convert set to an array.
func (s *set) List(item int) []int {
	s.mu.RLock()
	defer s.mu.RUnlock()

	i := 0
	l := make([]int, len(s.data))
	for val := range s.data {
		l[i] = val
		i++
	}

	return l
}
