// Code generated by "stringer -type=GenType -trimprefix=GenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenTypeInvalid-0]
	_ = x[GenTypeInt8-1]
	_ = x[GenTypeInt16-2]
	_ = x[GenTypeInt32-3]
	_ = x[GenTypeInt-4]
	_ = x[GenTypeInt64-5]
	_ = x[GenTypeUint8-6]
	_ = x[GenTypeUint16-7]
	_ = x[GenTypeUint32-8]
	_ = x[GenTypeUint-9]
	_ = x[GenTypeUint64-10]
	_ = x[GenTypeFloat32-11]
	_ = x[GenTypeFloat64-12]
	_ = x[GenTypeString-13]
	_ = x[GenTypeTime-14]
	_ = x[GenTypeEndTypes-15]
}

const _GenType_name = "InvalidInt8Int16Int32IntInt64Uint8Uint16Uint32UintUint64Float32Float64StringTimeEndTypes"

var _GenType_index = [...]uint8{0, 7, 11, 16, 21, 24, 29, 34, 40, 46, 50, 56, 63, 70, 76, 80, 88}

func (i GenType) String() string {
	if i < 0 || i >= GenType(len(_GenType_index)-1) {
		return "GenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenType_name[_GenType_index[i]:_GenType_index[i+1]]
}
