// Code generated by internal/numeric.tmpl, DO NOT EDIT.

package uint16set

import (
	"sync"
)

type set struct {
	mu   sync.RWMutex
	data map[uint16]struct{}
}

// New create and return instance of uint16 set
func New(uint16s ...uint16) *set {
	s := NewWithSize(len(uint16s))
	s.Adds(uint16s...)
	return s
}

// New create and return instance of uint16 set
func NewWithSize(size int) *set {
	return &set{
		data: make(map[uint16]struct{}, size),
	}
}

// Add item to the set.
func (s *set) Add(item uint16) {
	s.mu.Lock()
	defer s.mu.Unlock()

	s.data[item] = struct{}{}
}

// Add items to the set.
func (s *set) Adds(items ...uint16) {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, item := range items {
		s.data[item] = struct{}{}
	}
}

// Remove item from the set.
func (s *set) Remove(item uint16) {
	s.mu.Lock()
	defer s.mu.Unlock()

	delete(s.data, item)
}

// Remove items from the set.
func (s *set) Removes(items ...uint16) {
	s.mu.Lock()
	defer s.mu.Unlock()

	for _, item := range items {
		delete(s.data, item)
	}
}

// Exist determines whether the item is exists in the set.
func (s *set) Exist(item uint16) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	_, ok := s.data[item]
	return ok
}

// List convert set to an array.
func (s *set) List(item uint16) []uint16 {
	s.mu.RLock()
	defer s.mu.RUnlock()

	i := 0
	l := make([]uint16, len(s.data))
	for val := range s.data {
		l[i] = val
		i++
	}

	return l
}
